version: '3.8'

volumes:
  data-postgres:
    external: false

services:

  postgres:
    build: ./Postgresql
    container_name: postgresql-pizzaria
    environment:
      - POSTGRES_USER=${MY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${MY_POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./Postgresql/data-postgres:/var/lib/postgresql/data

  pgadmin:
    build: ./PGAdmin
    container_name: pgadmin-pizzaria
    depends_on:
      - postgres
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${MY_PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${MY_PGADMIN_PASSWORD}

  php:
    build: ./Alpine
    container_name: alpine-pizzaria
    depends_on:
      - postgres
    ports:
      - 8080:80
    volumes:
      - ./../project:/var/www/html/
    working_dir: "/var/www/html"
